// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3YnezD7_jts0_6ILYoajMXSKxaxIoIGM',
    appId: '1:1061341948351:web:6c8db278a01d964bd3990a',
    messagingSenderId: '1061341948351',
    projectId: 'objective-otter',
    authDomain: 'objective-otter.firebaseapp.com',
    storageBucket: 'objective-otter.appspot.com',
    measurementId: 'G-F1W4QLPT10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTVJBCpbpxudC1yOzaQTrixXzOI5CJiis',
    appId: '1:1061341948351:android:f44b7a72c08a2b00d3990a',
    messagingSenderId: '1061341948351',
    projectId: 'objective-otter',
    storageBucket: 'objective-otter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKms3ri8_e8YxMFvPTiVZtwIzZFo7ktNo',
    appId: '1:1061341948351:ios:18c5b0b6df463dfdd3990a',
    messagingSenderId: '1061341948351',
    projectId: 'objective-otter',
    storageBucket: 'objective-otter.appspot.com',
    iosBundleId: 'com.atketan.objectiveOtter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKms3ri8_e8YxMFvPTiVZtwIzZFo7ktNo',
    appId: '1:1061341948351:ios:18c5b0b6df463dfdd3990a',
    messagingSenderId: '1061341948351',
    projectId: 'objective-otter',
    storageBucket: 'objective-otter.appspot.com',
    iosBundleId: 'com.atketan.objectiveOtter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3YnezD7_jts0_6ILYoajMXSKxaxIoIGM',
    appId: '1:1061341948351:web:a111c12a583a9c6ad3990a',
    messagingSenderId: '1061341948351',
    projectId: 'objective-otter',
    authDomain: 'objective-otter.firebaseapp.com',
    storageBucket: 'objective-otter.appspot.com',
    measurementId: 'G-Z4FPK1NHM4',
  );
}
